package com.carbo.job.model.proposal.v2;

public enum ProposalRoleEnum {
    ROLE_SUPER_SALES_USER,
    ROLE_SALES_USER,
    ROLE_MANAGEMENT,
    ROLE_CLIENT,
    ROLE_SCHEDULER,
    ROLE_OPERATOR,
    ROLE_CREW_SCHEDULING,
    ROLE_FIELDCOORDINATOR,
    ROLE_PROCUREMENT,
    ROLE_SERVICEMANAGER,
    ROLE_DOCUMENT_REVIEWER
}
